version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  yada:
    image: bonux.yada/yada
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9009:9009"
    links:
      - db:database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"