version: '3'

services:
  sonar-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    links:
      - sonar-db:database
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: "jdbc:postgresql://database:5432/sonar"
    volumes:
      - "./libs/:/opt/sonarqube/extensions/plugins/"
