spring:
    datasource:
        url: "jdbc:h2:mem:yada;MODE=PostgreSQL"
    jpa:
      show-sql: true
      database: H2
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.H2Dialect